experiment_name: "experiment_2"

paths:
  logs_dir: "results/logs"
  results_dir: "results/experiment_2"

env: {}

steps:
  - name: "Organize dataset (highest-RMS segment as query)"
    enabled: true
    cmd: "python experiment_2.py"

  - name: "Extract MFCCs"
    enabled: true
    cmd: "python extract_mfccs.py"

  - name: "Extract Perch embeddings"
    enabled: true
    cmd: "python extract_embeddings.py"

  - name: "Generate feature fusions / embeddings"
    enabled: true
    cmd: "python generate_fusions.py"

  - name: "Evaluate (Perch embeddings: HNSW / IMENN)"
    enabled: true
    cmd: "python run_experiments_embeddings.py"

  - name: "Evaluate (MFCC embeddings: HNSW / IMENN)"
    enabled: true
    cmd: "python run_experiments_mfcc.py"
